version: '3.4'

services:
  nodejs-docker-kube:
    image: nodejs-docker-kube
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
